[package]
name = "solana_instruction"
version = "0.1.0"
edition = "2021"



[lib]
crate-type = ["cdylib","lib"]

[dependencies]
borsh = "0.9.3"
solana-program = "1.18.26"

[dev-dependencies]
solana-program-test = "1.18.26"
solana-sdk = "1.18.26"
tokio = "1.45.1"
